version: '3.8'
services:
  db:
    build:
      context: docker
      dockerfile: db.Dockerfile
    container_name: PostgresExchange
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data