server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/exchange
    username: exchange_user
    password: exchange123
    properties:
      schema: exchange

reports:
  cron: "0 0 20 * * *"